//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicSpace
    {
        public Nullable<int> ResidentID { get; set; }
        public string StaffID { get; set; }
        public string seq { get; set; }
        public string barrierName { get; set; }
        public string LocationID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateTimeNow { get; set; }
        public string 借用審核 { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ResidentDataTable ResidentDataTable { get; set; }
        public virtual StaffDataTable StaffDataTable { get; set; }
    }
}
