//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PublicSpace
    {
        [Display(Name ="住戶ID")]
        public int ResidentID { get; set; }
        [Display(Name = "管理員ID")]
        public string StaffID { get; set; }
        [Display(Name = "資料ID")]
        public string seq { get; set; }
        [Display(Name = "借用人姓名")]
        public string barrierName { get; set; }
        [Display(Name = "借用場地")]
        public string LocationID { get; set; }
        [Display(Name = "借用時間")]
        public System.DateTime StartTime { get; set; }
        [Display(Name = "歸還時間")]
        public System.DateTime EndTime { get; set; }
        [Display(Name = "借用事由")]
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateTimeNow { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ResidentDataTable ResidentDataTable { get; set; }
        public virtual StaffDataTable StaffDataTable { get; set; }
    }
}
