//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnPackage
    {
        public int ReturnDataID { get; set; }
        public Nullable<System.DateTime> ReturnArrivalDate { get; set; }
        public string ReturnCompanyID { get; set; }
        public string Returnee { get; set; }
        public Nullable<int> ReturneeID { get; set; }
        public Nullable<bool> Sign { get; set; }
        public string StaffID { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
    
        public virtual PackageCompany PackageCompany { get; set; }
        public virtual ResidentDataTable ResidentDataTable { get; set; }
    }
}
