//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDataTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffDataTable()
        {
            this.BulletinBoard = new HashSet<BulletinBoard>();
            this.ParkingManagement = new HashSet<ParkingManagement>();
            this.UserAccount = new HashSet<UserAccount>();
            this.PublicSpace = new HashSet<PublicSpace>();
            this.PackageTable = new HashSet<PackageTable>();
        }
    
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string StaffPhone { get; set; }
        public string StaffLINE_ID { get; set; }
        public bool OnWork { get; set; }
        public string ShiftID { get; set; }
        public byte[] img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulletinBoard> BulletinBoard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingManagement> ParkingManagement { get; set; }
        public virtual ShiftTable ShiftTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicSpace> PublicSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageTable> PackageTable { get; set; }
    }
}
