//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IoTWeb.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號編號 的當地語系化字串。
        /// </summary>
        public static string AspUserId {
            get {
                return ResourceManager.GetString("AspUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住戶社區地址 的當地語系化字串。
        /// </summary>
        public static string CommunityAddress {
            get {
                return ResourceManager.GetString("CommunityAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貨運公司名稱 的當地語系化字串。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子信箱 的當地語系化字串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 入職時間 的當地語系化字串。
        /// </summary>
        public static string EntryDate {
            get {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 照片 的當地語系化字串。
        /// </summary>
        public static string img {
            get {
                return ResourceManager.GetString("img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離職時間 的當地語系化字串。
        /// </summary>
        public static string LeaveDate {
            get {
                return ResourceManager.GetString("LeaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在住情形 的當地語系化字串。
        /// </summary>
        public static string Living {
            get {
                return ResourceManager.GetString("Living", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在職狀態 的當地語系化字串。
        /// </summary>
        public static string OnWork {
            get {
                return ResourceManager.GetString("OnWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 包裹抵達日期 的當地語系化字串。
        /// </summary>
        public static string PackageArrivalDate {
            get {
                return ResourceManager.GetString("PackageArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貨運公司 的當地語系化字串。
        /// </summary>
        public static string PackageCompany {
            get {
                return ResourceManager.GetString("PackageCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貨運公司編號 的當地語系化字串。
        /// </summary>
        public static string PackageCompanyID {
            get {
                return ResourceManager.GetString("PackageCompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 包裹編號 的當地語系化字串。
        /// </summary>
        public static string PackageID {
            get {
                return ResourceManager.GetString("PackageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收件人 的當地語系化字串。
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住戶編號 的當地語系化字串。
        /// </summary>
        public static string ResidentID {
            get {
                return ResourceManager.GetString("ResidentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住戶身份證字號 的當地語系化字串。
        /// </summary>
        public static string ResidentIDNumber {
            get {
                return ResourceManager.GetString("ResidentIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住戶LINE 的當地語系化字串。
        /// </summary>
        public static string ResidentLINE_ID {
            get {
                return ResourceManager.GetString("ResidentLINE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住戶名字 的當地語系化字串。
        /// </summary>
        public static string ResidentName {
            get {
                return ResourceManager.GetString("ResidentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住戶電話 的當地語系化字串。
        /// </summary>
        public static string ResidentPhone {
            get {
                return ResourceManager.GetString("ResidentPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退貨日期 的當地語系化字串。
        /// </summary>
        public static string ReturnArrivalDate {
            get {
                return ResourceManager.GetString("ReturnArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貨運公司編號 的當地語系化字串。
        /// </summary>
        public static string ReturnCompanyID {
            get {
                return ResourceManager.GetString("ReturnCompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 包裹編號 的當地語系化字串。
        /// </summary>
        public static string ReturnDataID {
            get {
                return ResourceManager.GetString("ReturnDataID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退件人 的當地語系化字串。
        /// </summary>
        public static string Returnee {
            get {
                return ResourceManager.GetString("Returnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住戶編號 的當地語系化字串。
        /// </summary>
        public static string ReturneeID {
            get {
                return ResourceManager.GetString("ReturneeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限 的當地語系化字串。
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 值班別編號 的當地語系化字串。
        /// </summary>
        public static string ShiftID {
            get {
                return ResourceManager.GetString("ShiftID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽收 的當地語系化字串。
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽收日期 的當地語系化字串。
        /// </summary>
        public static string SignedDate {
            get {
                return ResourceManager.GetString("SignedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作人員(保全)編號 的當地語系化字串。
        /// </summary>
        public static string StaffID {
            get {
                return ResourceManager.GetString("StaffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作人員(保全)LINE 的當地語系化字串。
        /// </summary>
        public static string StaffLINE_ID {
            get {
                return ResourceManager.GetString("StaffLINE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作人員(保全)名字 的當地語系化字串。
        /// </summary>
        public static string StaffName {
            get {
                return ResourceManager.GetString("StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作人員(保全)連絡電話 的當地語系化字串。
        /// </summary>
        public static string StaffPhone {
            get {
                return ResourceManager.GetString("StaffPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
